service: norm-service

package:
  individually: true
  exclude:
    - node_modules/**
    - data/**
    - data-full/**
    - headers-data/**
    - __pycache__/**
    - .git/**
    - .circleci/**
    - .mypy_cache/**
    - .ipynb_checkpoints/**
    - .gitignore
    - .vscode/**
    - dev/**
functions:
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get
  norm_http:
    handler: handler.norm_handler_http
    events:
      - http:
          path: '/normalize'
          method: post
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$')

plugins:

  - serverless-python-requirements
  - serverless-offline
