service: srcbot-normalization-service

custom:
  stage: ${opt:stage, self:provider.stage} # shortcut for current stage
  serverless-offline:
    resourceRoutes: true
    debug: true
    port: 4000

#  serverless-offline-sns:
#    port: 4002 # a free port for the sns server to run on
#    debug: true

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  
  memorySize: 256 # optional, in MB, default is 1024
 #timeout: 62 # optional, in seconds, default is 6
  environment:
  #  STAGE: ${self:custom.stage}
    APP_AWS_REGION: eu-central-1
    REGION_NAME: eu-central-1
    MISSING_QUEUE_URL: https://sqs.eu-central-1.amazonaws.com/202439666482/missing-mapping
    MISSING_QUEUE_NAME: missing-mapping
    INCOMING_SNS_TOPIC: arn:aws:sns:eu-central-1:202439666482:crawler-new-item #-${self:provider.stage}
    OUTGOING_SNS_TOPIC: arn:aws:sns:eu-central-1:202439666482:norm-new-item-${self:provider.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
        - "sqs:ListQueues"
        - "sns:Publish"

      Resource: 
        - arn:aws:sqs:eu-central-1:202439666482:missing-mapping
        - arn:aws:sns:eu-central-1:202439666482:norm-new-item-dev #${self:provider.stage}
        - arn:aws:sns:eu-central-1:202439666482:norm-new-item-production #${self:provider.stage}

package:
  exclude:
    - node_modules/**
    - data/**
    - data-full/**
    - headers-data/**
    - __pycache__/**
    - .git/**
    - .circleci/**
    - .mypy_cache/**
    - .ipynb_checkpoints/**
    - .gitignore
    - .vscode/**
    - dev/**
functions:
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get
  norm_sns:
    handler: handler.norm_handler_sns
    events:
      - sns:
            arn: arn:aws:sns:eu-central-1:202439666482:crawler-new-item #-${self:provider.stage}
  norm_http:
    handler: handler.norm_handler_http
    events:
      - http:
          path: '/normalize'
          method: post
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$')

plugins:

  - serverless-python-requirements
  - serverless-offline
#  - serverless-offline-sns
