# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build-job:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo pip3 install pipenv
            pipenv install --dev
            
      - save_cache:
          paths:
            - /home/circleci/.cache
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            pipenv run python -m unittest

      # more tests!
      - run:
          name: run more tests
          command: |
            pipenv run mypy normalization/__init__.py  --ignore-missing-imports
  deploy-job:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            sudo pip3 install pipenv
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            sudo apt-get update
            sudo apt-get install -y nodejs
            sudo apt-get install npm
            sudo npm i -g npm
            sudo npm i -g serverless
            npm install
            pipenv install
      - save_cache:
          paths:
            - /home/circleci/.cache
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}
      - run:
          name: deploy sls
          command: |
            pipenv run sls deploy
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master