version: 2

jobs:
  build-deploy-job:
    working_directory: ~/tmp/workspace
    docker:
      - image: srcbot/docker-python-nodejs
        environment:
          LC_ALL: "C.UTF-8"
          LANG: "C.UTF-8"
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: get common deps.
          command: |
            ./build.sh $CIRCLE_BRANCH

      - run:
          name: install dependencies
          command: |
            pipenv install --system

      - save_cache:
          paths:
            - /home/circleci/.cache
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      # run tests!
      - run:
          name: run tests
          command: |
            python -m unittest

      # more tests!
      - run:
          name: run more tests
          command: |
            pipenv run mypy normalization/__init__.py  --ignore-missing-imports  --follow-imports=skip
            
      - run:
        name: deploy
        command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                sls deploy --stage production --region eu-central-1
            elif [ "${CIRCLE_BRANCH}" == "dev" ]; then
              sls deploy --stage dev --region eu-central-1
            fi
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-deploy-job
